title: deSouq
baseURL: /
params:
  palette: yellow
  snipcart_api_key: ''
  favicon: /images/deSouq logo SM.jpg
  logo_light: /images/cool-whale.jpg
  bg_image_primary: /images/header.jpg
  bg_image_primary_opacity: 60
  bg_image_secondary: /images/magnificent-velociraptor.png
  bg_image_product: /images/dS logo 9.png
  main_menu:
    - type: action
      template: action
      title: Store
      url: /store
      style: link
    - type: action
      template: action
      title: About
      url: /about
      style: primary
    - type: action
      template: action
      title: FAQ
      url: /faq
      style: link
  footer_text: Copyright 2021 Planty Inc. All rights reserved.
  domain: 'https://desouq-75cb1.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
